# Generated by Django 4.0.6 on 2022-07-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesMate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quoteAuthor',
            field=models.CharField(default='beena changela', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='quoteContent',
            field=models.CharField(max_length=500),
        ),
    ]
