# Generated by Django 4.0.6 on 2022-07-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotesMate', '0002_quote_quoteauthor_alter_quote_quotecontent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote',
            new_name='Quotelist',
        ),
    ]
